Introducción a TensorFlow y Keras
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/neural-networks/tree/master/) para acceder al repositorio online.

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/neural-networks/tree/master/) para explorar el repositorio usando `nbviewer`. 

---

Sitios web:

* https://keras.io


* https://www.tensorflow.org

---

### Operaciones matemáticas básicas

In [1]:
import tensorflow as tf
import numpy as np

/Users/jdvelasq/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


En el siguiente ejemplo se evaluará la expresión 5 * 2 - (3 + 2). Esta expresión puede ser representada a través del siguiente árbol sintáctico:

     [-]
      +--- [*]
      |     +---- [5]
      |     +---- [2]
      |
      +--- [+]
            +---- [3]
            +---- [2]

Note que en esta expresión el nodo con la constante 2 es común a ambas ramas y podría representarse de forma optimizada como:

     [-]
      +--- [*]
      |     +---- [5]
      |     +-----------+
      |                 |
      +--- [+]         [2] 
            +---- [3]   |
            +-----------+ 

Para realizar la evaluación usando `TensorFlow`, se debe construir explícitamente el grafo, para lo cual se enumeran los nodos de la siguiente forma:

     [-] (node6)
      +--- [*] (node4)
      |     +---- [5] (node1)
      |     +---------------------+
      |                           |
      +--- [+] (node5)           [2] (node2)
            +---- [3] (node3)     |
            +---------------------+ 


In [2]:
node1 = tf.constant(5.0)  
node2 = tf.constant(2.0)  
node3 = tf.constant(3.0)  
node4 = tf.multiply(node1, node2)
node5 = tf.add(node3, node2)
node6 = tf.subtract(node4, node5)

In [3]:
## el grafo puede accederse asi:
tf.get_default_graph()

Para poder ejecutar los cálculos es necesario abrir una sesión.

In [4]:
## abre la sesión y luego la cierra
with tf.Session() as sess:
    outs = sess.run(node6)          ## realiza la evaluación
    print("outs = {}".format(outs)) ## imprime el resultado de la evaluación

outs = 5.0


In [5]:
## Para computar el resultado en un nodo se puede usar eval()
with tf.Session() as sess:
    print('node6 = {}'.format(node6.eval()))
    print('node4 = {}'.format(node4.eval()))

node6 = 5.0
node4 = 10.0


In [6]:
## run() admite una lista de nodos a evaluar
with tf.Session() as sess:
    outs = sess.run([node6, node4, node5])
    print("outs = {}".format(outs))

outs = [5.0, 10.0, 5.0]


In [7]:
## la sesión puede ser almacenada en una variable
## y usada en cálculos posteriores
sess = tf.Session()             ## abre la sesion (en IPython use tf.InteractiveSession())
outs = sess.run(node6)          ## evalua el grafo y almacena el resultado
sess.close()                    ## cierra la sesión
print("outs = {}".format(outs)) ## imprime el resultado de la evaluación

outs = 5.0


A continuación se resumen las operaciones mas comunes (la lista completa de operadores puede ser consultada en https://www.tensorflow.org/api_guides/python/math_ops)

    Operacion               equivalente
    --------------------------------------
    tf.add(a, b)            a + b
    tf.multiply(a, b)       a * b
    tf.subtract(a, b)       a - b
    tf.divide(a, b)         a / b
    tf.pow(a, b)            a ** b
    tf.mod(a, b)            a % b
    
    tf.abs(a)               abs(a)
    tf.square(a)            a ** 2
    tf.sqrt(a)              sqrt(a)
    tf.exp(a)               exp(a)
    tf.negative(a)          -a
    tf.sigmoid(a)           1 / (1 + exp(-a))
    tf.sign                 sign(a)
    tf.maximum
    tf.minimum
    
    tf.logical_and(a, b)    a & b
    tf.logical_or(a, b)     a | b   
    tf.greater(a, b)        a > b
    tf.greater_equal(a, b)  a >= b
    tf.less_equal(a, b)     a <= b
    tf.less(a, b)           a < b
    tf.logical_not(a)       ~a 
    tf.equal(a, b)          a == b
    tf.not_equal            a != b
    


---
**Ejercicio.--** Compute $5*2^2 + 3 * 5 - 18$ usando TensorFlow.

---

### Matrices

In [8]:
## Esta opción abre la sesión interactiva y la 
## mantiene abierta
tf.InteractiveSession()

In [9]:
a = np.ones((3,3))
b = tf.convert_to_tensor(a)
b.eval()
#sess.run(b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
tf.zeros((2,2)).eval()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [11]:
tf.ones((2,2)).eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [12]:
tf.random_normal((3,2),     ## shape
                 0,         ## mean
                 1).eval()  ## sd

array([[-0.26979545,  0.5981732 ],
       [ 0.13635306,  0.75549424],
       [ 1.4228015 , -0.66110176]], dtype=float32)

In [13]:
tf.truncated_normal((3,2),  ## shape
                    0,      ## mean
                    1).eval()     ## sd

array([[ 1.9580271e-04,  6.2689185e-01],
       [-7.0928586e-01,  2.4103402e-01],
       [ 2.4478497e-01, -1.0959780e-01]], dtype=float32)

In [14]:
tf.random_uniform((3,2),     ## shape
                  0,         ## minval
                  1).eval()  ## maxval

array([[0.2325803 , 0.6902174 ],
       [0.75136256, 0.12303627],
       [0.10225999, 0.6465963 ]], dtype=float32)

In [15]:
tf.fill((3,2),      ## shape
        4).eval()   ## value

array([[4, 4],
       [4, 4],
       [4, 4]], dtype=int32)

In [16]:
tf.linspace(0.0, 1.0, 11).eval()

array([0.        , 0.1       , 0.2       , 0.3       , 0.4       ,
       0.5       , 0.6       , 0.7       , 0.8       , 0.90000004,
       1.        ], dtype=float32)

In [17]:
tf.constant([[1,2,3], 
             [4,5,6]]).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [18]:
tf.random_shuffle(tf.constant([1,2,3,4,5,6])).eval()

array([6, 5, 2, 1, 3, 4], dtype=int32)

In [19]:
m = tf.constant([[1,2,3], 
                 [4,5,6]])

In [20]:
## suma de las columnas
tf.reduce_sum(m, reduction_indices = 0).eval()

array([5, 7, 9], dtype=int32)

In [21]:
## suma de las filas
tf.reduce_sum(m, reduction_indices = 1).eval()

array([ 6, 15], dtype=int32)

In [22]:
## suma de todos los elementos
tf.reduce_sum(m).eval()

21

`TensorFlow` implementa las siguiente funciones para reducir un tensor (https://www.tensorflow.org/api_guides/python/math_ops#Reduction)

    tf.reduce_sum
    tf.reduce_prod
    tf.reduce_min
    tf.reduce_max
    tf.reduce_mean
    tf.reduce_all
    tf.reduce_any
    tf.reduce_logsumexp
    tf.count_nonzero
    tf.accumulate_n
    tf.einsum
    

In [23]:
## dimensiones
m = tf.constant([[1,2,3], 
                 [4,5,6]])
m.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [24]:
a = m + m
a.eval()

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)

In [25]:
tf.reshape(m,(1,6)).eval()

array([[1, 2, 3, 4, 5, 6]], dtype=int32)

In [26]:
tf.reshape(m,(3,2)).eval()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [27]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 0], [0, 6]])
tf.accumulate_n([a, b, a]).eval()  # [[7, 4], [6, 14]]

array([[ 7,  4],
       [ 6, 14]], dtype=int32)

In [28]:
tf.add_n([a, b, a]).eval()

array([[ 7,  4],
       [ 6, 14]], dtype=int32)

In [29]:
tf.argmax(tf.constant([1,3,2,4,0])).eval()

3

In [30]:
tf.argmin(tf.constant([1,3,2,4,0])).eval()

4

In [31]:
x = tf.constant([10.0, -1.0])
y = tf.map_fn(lambda m: tf.cond(tf.greater_equal(m, 0.0), 
                                true_fn = lambda: tf.constant(1.), 
                                false_fn = lambda : tf.constant(0.0)),
              x)

with tf.Session() as sess:
    print(sess.run(y))

[1. 0.]


In [32]:
x = tf.constant([[10.0], [-1.0]])
y = tf.map_fn(lambda m: tf.cond(tf.greater_equal(m[0], 0.0), 
                                true_fn = lambda: tf.constant([1.]), 
                                false_fn = lambda : tf.constant([0.0])),
              x)

with tf.Session() as sess:
    print(sess.run(y))
    

[[1.]
 [0.]]


### Variables y Placeholders

Las variables pueden entenderse como las variables locales de una función, las cuales no pueden ser accesadas desde el exterior de la función. Los placeholders son equivalentes a los parámetros, los cuales pueden tomar cualquier valor cuando se llama la función. En el siguiente ejemplo se evalua la expresión a * b - (b + c) para diferentes valores de a, b y c.

     [-] (node6)
      +--- [*] (node4)
      |     +---- [a] (node1)
      |     +---------------------+
      |                           |
      +--- [+] (node5)           [b] (node2)
            +---- [c] (node3)     |
            +---------------------+ 

In [33]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = tf.placeholder(tf.float32)

node4 = tf.multiply(a, b)
node5 = tf.add(c, b)
node6 = tf.subtract(node4, node5)

with tf.Session() as sess:
    print(sess.run(node6, feed_dict={a: 5, b:3, c:2}))
    print(sess.run(node6, feed_dict={a: 4, b:2, c:3}))
    print(sess.run(node6, feed_dict={a: 4, b:3, c:1}))

10.0
3.0
8.0


In [34]:
##
## la misma operación pero matricial
##
a = tf.placeholder(tf.float32, shape=(3,3))
b = tf.placeholder(tf.float32, shape=(3,3))
c = tf.placeholder(tf.float32, shape=(3,3))

node4 = tf.multiply(a, b)
node5 = tf.add(c, b)
node6 = tf.subtract(node4, node5)

with tf.Session() as sess:    
    print(sess.run(node6, feed_dict={a: [[1, 0, 0,],
                                         [0, 1, 0,],
                                         [0, 0, 1,]],
                                     b: np.random.normal(size=(3,3)), 
                                     c: np.random.normal(size=(3,3))}))

[[-0.46384197 -1.2342931   0.5352072 ]
 [-2.9913986  -2.8914263   0.07552639]
 [ 1.3343722   1.0699565  -0.2756308 ]]


El siguiente ejemplo presente un acumulador para el calculo de $n = n + 1$.

    [=] (node1)  
     +---[n]
     +---[+] (node0)
          +----[n]
          +----[1]
     

In [35]:
## crea la variable y la inicializa a cero
n = tf.Variable(0)

## arbol sintactico que representa las operaciones
node0 = tf.add(n, tf.constant(1))
node1 = tf.assign(n, node0)

## evalua
with tf.Session() as sess:
    
    ## las variables deben ser inicializadas antes
    ## de usarse
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        ## el valor de las variables se retiene entre
        ## las llamadas a run()
        print(sess.run(node1))

1
2
3
4
5


In [36]:
## crea la variable y la inicializa a cero
n = tf.Variable(0)

## arbol sintactico que representa las operaciones
## se usa tf.assign_add para simplificar el arbol
## tambien existe tf.assign_sub
node0 = tf.assign_add(n, tf.constant(1))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        print(sess.run(node0))

1
2
3
4
5


---
**Ejercicio.--** Indique para que sirven las siguientes funciones del modulo `tf` y realice un ejemplo:

    tf.clip_by_value
    tf.clip_by_norm
    tf.clip_by_average_norm
    tf.clip_by_global_norm
    tf.clip_by_norm
    tf.concat
    tf.case
    tf.cond
    tf.cumprod
    tf.cumsum
    tf.diag
    tf.inverse_permutation
    tf.log_sigmoid 
    tf.map_fn
    
    tf.matrix_inverse
    tf.matrix_diag
    tf.matrix_set_diag
    tf.matrix_solve
    tf.matrix_transpose
    tf.parallel_stack
    tf.stack
    tf.random_shuffle
    tf.reverse
    
    tf.maximum
    tf.minimum
    
---

### Funciones de activación

In [37]:
tf.nn.relu([-3., 3., 10.]).eval()

array([ 0.,  3., 10.], dtype=float32)

In [38]:
tf.nn.relu6([-3., 3., 10.]).eval()

array([0., 3., 6.], dtype=float32)

In [39]:
tf.nn.sigmoid([-1., 0., 1.]).eval()

array([0.26894143, 0.5       , 0.7310586 ], dtype=float32)

In [40]:
tf.nn.softsign([-1., 0., -1.]).eval()

array([-0.5,  0. , -0.5], dtype=float32)

In [41]:
tf.nn.softplus([-1., 0., -1.]).eval()

array([0.31326166, 0.6931472 , 0.31326166], dtype=float32)

In [42]:
tf.nn.elu([-1., 0., -1.]).eval()

array([-0.63212055,  0.        , -0.63212055], dtype=float32)

### Optimización de modelos (regresión lineal)

El siguiente ejemplo ilustra la construcción y estimación de un modelo de regresión lineal usando `TensorFlow`.

In [43]:
## 
## El modelo es el siguiente:
##
##    y = w' x + b
##
## Muestra de datos:
##
##    x      y
## -------------
##  1.1   1.98
##  2.0   3.01
##  2.6   3.51
##  3.2   4.34
##  4.3   5.32
##

## x y y son constantes
x = tf.constant([ 1.1,  2.0,  2.6,  3.2 ,  4.3])
y = tf.constant([ 1.98, 3.01, 3.51, 4.34 , 5.32])

## w y b son las variables a estimar
w = tf.Variable(0.0)
b = tf.Variable(0.0)

## Define el modelo
m = tf.add(tf.multiply(x, w), 
           b)

## Define la función de error
sse = tf.reduce_sum(tf.square(m - y)) # sum of the squares

## Inicializa el optimizador
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.0001)

## Minimiza la función de error
opt = optimizer.minimize(sse)

## estima el modelo
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(1000):
        sess.run(opt)
        if (i % 200 == 0):
            print(sess.run(sse))
        
    print(sess.run([w, b]))


71.14235
2.073927
0.21756828
0.16102216
0.1530072
[1.1840729, 0.45279855]


---
**Ejercicio.--** Modifique el código anterior para que pueda operar sobre datos matriciales.

---


Introducción a TensorFlow y Keras
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/neural-networks/tree/master/) para acceder al repositorio online.

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/neural-networks/tree/master/) para explorar el repositorio usando `nbviewer`. 